[versions]
#region Plugins
androidKotlin = "1.8.10"
androidApplication = "7.4.1"
androidLibrary = "7.4.1"
#endregion Plugins

#region Android
appCompat = "1.6.0"
coreKtx = "1.9.0"
#endregion Android

#region Google
material = "1.8.0"
ksp = "1.8.10-1.0.9"
#endregion Google

#region Test
kotest = "5.5.5"
#endregion Test

#region Kotlin
kotlin = "1.8.10"
#endregion Kotlin

#region Kotlin
kotlinpoetKsp = "1.12.0"
#endregion Kotlin

[libraries]

#region Android
appCompat = { module = "androidx.appcompat:appcompat", version.ref = "appCompat" }
coreKtx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
#endregion Android

#region Google
material = { module = "com.google.android.material:material", version.ref = "material" }
symbolProcessingApi = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
symbolProcessing = { module = "com.google.devtools.ksp:symbol-processing", version.ref = "ksp" }
#endregion Google

#region Test
kotestRunnerJunit = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotestAssertionsCore = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotestProperty = { module = "io.kotest:kotest-property", version.ref = "kotest" }
#endregion Test

#region Kotlin
kotlinReflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlinStdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
#endregion Kotli

#region Squareup
kotlinpoetKsp = { module = "com.squareup:kotlinpoet-ksp", version.ref = "kotlinpoetKsp" }
#endregion Squareup

[bundles]
android = ["appCompat", "coreKtx"]
kotest = ["kotestRunnerJunit", "kotestAssertionsCore", "kotestProperty"]

[plugins]
androidApplication = { id = "com.android.application", version.ref = "androidApplication" }
androidLibrary = { id = "com.android.library", version.ref = "androidLibrary" }
androidKotlin = { id = "org.jetbrains.kotlin.android", version.ref = "androidKotlin" }